In [1]:
import pandas as pd 
import requests 
import numpy as np

In [2]:
TorontoRD=pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")[0] 
TorontoRD['Borough'] = TorontoRD['Borough'].replace('Not assigned', np.nan)
TorontoRD = TorontoRD.dropna(axis=0, subset=['Borough']) 
TorontoRD['Neighbourhood'] = TorontoRD['Neighbourhood'].replace('Not assigned', np.nan)
TorontoRD.Neighbourhood.fillna(TorontoRD.Borough,inplace=True) 
TorontoRD = TorontoRD.groupby(by=['Postcode','Borough'],sort = False).agg(lambda x: ','.join(x))
TorontoRD=TorontoRD.reset_index() 
Toronto_df=TorontoRD 
Toronto_df.head(10)

  Postcode           Borough                    Neighbourhood
0      M3A        North York                        Parkwoods
1      M4A        North York                 Victoria Village
2      M5A  Downtown Toronto         Harbourfront,Regent Park
3      M6A        North York  Lawrence Heights,Lawrence Manor
4      M7A      Queen's Park                     Queen's Park
5      M9A         Etobicoke                 Islington Avenue
6      M1B       Scarborough                    Rouge,Malvern
7      M3B        North York                  Don Mills North
8      M4B         East York   Woodbine Gardens,Parkview Hill
9      M5B  Downtown Toronto          Ryerson,Garden District

In [3]:

Toronto_df.shape

(103, 3)

In [4]:
!pip install geocoder 
import geocoder

Requirement already satisfied: geocoder in /opt/conda/envs/Python36/lib/python3.6/site-packages (1.38.1)
Requirement already satisfied: click in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (7.0)
Requirement already satisfied: six in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (1.12.0)
Requirement already satisfied: requests in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (2.21.0)
Requirement already satisfied: ratelim in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: future in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (0.17.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (1.24.1)
Requirement already satisfied: decorator in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ratelim->geocoder) (4.3.2)

In [5]:
print('Import Complete')

Import Complete

In [6]:
path='http://cocl.us/Geospatial_data'
Toronto_new=pd.read_csv(path)
Toronto_new.head(10)

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476
5         M1J  43.744734 -79.239476
6         M1K  43.727929 -79.262029
7         M1L  43.711112 -79.284577
8         M1M  43.716316 -79.239476
9         M1N  43.692657 -79.264848

In [7]:
Toronto_df=Toronto_df.sort_values(by=['Postcode'], axis=0)
Toronto_df.head()

   Postcode      Borough                         Neighbourhood
6       M1B  Scarborough                         Rouge,Malvern
12      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
18      M1E  Scarborough       Guildwood,Morningside,West Hill
22      M1G  Scarborough                                Woburn
26      M1H  Scarborough                             Cedarbrae

In [9]:
Toronto_df.reset_index(inplace=True)
Toronto_df.drop('index', inplace=True, axis=1)
Toronto_df.head()

  Postcode      Borough                         Neighbourhood
0      M1B  Scarborough                         Rouge,Malvern
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough       Guildwood,Morningside,West Hill
3      M1G  Scarborough                                Woburn
4      M1H  Scarborough                             Cedarbrae

In [10]:
Toronto_df=Toronto_df.rename(columns={'Postcode':'Postal Code'})
Toronto_df.head(10)

  Postal Code      Borough                                  Neighbourhood
0         M1B  Scarborough                                  Rouge,Malvern
1         M1C  Scarborough           Highland Creek,Rouge Hill,Port Union
2         M1E  Scarborough                Guildwood,Morningside,West Hill
3         M1G  Scarborough                                         Woburn
4         M1H  Scarborough                                      Cedarbrae
5         M1J  Scarborough                            Scarborough Village
6         M1K  Scarborough      East Birchmount Park,Ionview,Kennedy Park
7         M1L  Scarborough                  Clairlea,Golden Mile,Oakridge
8         M1M  Scarborough  Cliffcrest,Cliffside,Scarborough Village West
9         M1N  Scarborough                     Birch Cliff,Cliffside West

In [11]:
Toronto_df[['Latitude','Longitude']]=Toronto_new[['Latitude','Longitude']]
Toronto_df.head(10)

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"East Birchmount Park,Ionview,Kennedy Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea,Golden Mile,Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffcrest,Cliffside,Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff,Cliffside West",43.692657,-79.264848

In [13]:
print('End of Second Part!')

End of Second Part!